/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Connection_LED */
#define Connection_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Connection_LED_0_INBUF_ENABLED 0u
#define Connection_LED_0_INIT_DRIVESTATE 0u
#define Connection_LED_0_INIT_MUXSEL 0u
#define Connection_LED_0_INPUT_SYNC 2u
#define Connection_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Connection_LED_0_NUM 5u
#define Connection_LED_0_PORT GPIO_PRT10
#define Connection_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Connection_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Connection_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Connection_LED_INBUF_ENABLED 0u
#define Connection_LED_INIT_DRIVESTATE 0u
#define Connection_LED_INIT_MUXSEL 0u
#define Connection_LED_INPUT_SYNC 2u
#define Connection_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Connection_LED_NUM 5u
#define Connection_LED_PORT GPIO_PRT10
#define Connection_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Connection_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
