/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_1 */
#define Pin_1_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_1_0_INBUF_ENABLED 0u
#define Pin_1_0_INIT_DRIVESTATE 1u
#define Pin_1_0_INIT_MUXSEL 0u
#define Pin_1_0_INPUT_SYNC 2u
#define Pin_1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_0_NUM 0u
#define Pin_1_0_PORT GPIO_PRT10
#define Pin_1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_1_INBUF_ENABLED 0u
#define Pin_1_INIT_DRIVESTATE 1u
#define Pin_1_INIT_MUXSEL 0u
#define Pin_1_INPUT_SYNC 2u
#define Pin_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_NUM 0u
#define Pin_1_PORT GPIO_PRT10
#define Pin_1_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_rx */
#define UART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_0_INBUF_ENABLED 1u
#define UART_rx_0_INIT_DRIVESTATE 1u
#define UART_rx_0_INIT_MUXSEL 18u
#define UART_rx_0_INPUT_SYNC 2u
#define UART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_0_NUM 0u
#define UART_rx_0_PORT GPIO_PRT5
#define UART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_INBUF_ENABLED 1u
#define UART_rx_INIT_DRIVESTATE 1u
#define UART_rx_INIT_MUXSEL 18u
#define UART_rx_INPUT_SYNC 2u
#define UART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_NUM 0u
#define UART_rx_PORT GPIO_PRT5
#define UART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT5
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT5
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Power_LED */
#define Power_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Power_LED_0_INBUF_ENABLED 0u
#define Power_LED_0_INIT_DRIVESTATE 1u
#define Power_LED_0_INIT_MUXSEL 0u
#define Power_LED_0_INPUT_SYNC 2u
#define Power_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Power_LED_0_NUM 1u
#define Power_LED_0_PORT GPIO_PRT9
#define Power_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Power_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Power_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Power_LED_INBUF_ENABLED 0u
#define Power_LED_INIT_DRIVESTATE 1u
#define Power_LED_INIT_MUXSEL 0u
#define Power_LED_INPUT_SYNC 2u
#define Power_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Power_LED_NUM 1u
#define Power_LED_PORT GPIO_PRT9
#define Power_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Power_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Voltage_OK */
#define Voltage_OK_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Voltage_OK_0_INBUF_ENABLED 0u
#define Voltage_OK_0_INIT_DRIVESTATE 0u
#define Voltage_OK_0_INIT_MUXSEL 0u
#define Voltage_OK_0_INPUT_SYNC 2u
#define Voltage_OK_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Voltage_OK_0_NUM 4u
#define Voltage_OK_0_PORT GPIO_PRT9
#define Voltage_OK_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Voltage_OK_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Voltage_OK_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Voltage_OK_INBUF_ENABLED 0u
#define Voltage_OK_INIT_DRIVESTATE 0u
#define Voltage_OK_INIT_MUXSEL 0u
#define Voltage_OK_INPUT_SYNC 2u
#define Voltage_OK_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Voltage_OK_NUM 4u
#define Voltage_OK_PORT GPIO_PRT9
#define Voltage_OK_SLEWRATE CY_GPIO_SLEW_FAST
#define Voltage_OK_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Connection_LED */
#define Connection_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Connection_LED_0_INBUF_ENABLED 0u
#define Connection_LED_0_INIT_DRIVESTATE 0u
#define Connection_LED_0_INIT_MUXSEL 0u
#define Connection_LED_0_INPUT_SYNC 2u
#define Connection_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Connection_LED_0_NUM 0u
#define Connection_LED_0_PORT GPIO_PRT9
#define Connection_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Connection_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Connection_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Connection_LED_INBUF_ENABLED 0u
#define Connection_LED_INIT_DRIVESTATE 0u
#define Connection_LED_INIT_MUXSEL 0u
#define Connection_LED_INPUT_SYNC 2u
#define Connection_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Connection_LED_NUM 0u
#define Connection_LED_PORT GPIO_PRT9
#define Connection_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Connection_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Overvoltage_LED */
#define Overvoltage_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Overvoltage_LED_0_INBUF_ENABLED 0u
#define Overvoltage_LED_0_INIT_DRIVESTATE 0u
#define Overvoltage_LED_0_INIT_MUXSEL 0u
#define Overvoltage_LED_0_INPUT_SYNC 2u
#define Overvoltage_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Overvoltage_LED_0_NUM 2u
#define Overvoltage_LED_0_PORT GPIO_PRT9
#define Overvoltage_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Overvoltage_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Overvoltage_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Overvoltage_LED_INBUF_ENABLED 0u
#define Overvoltage_LED_INIT_DRIVESTATE 0u
#define Overvoltage_LED_INIT_MUXSEL 0u
#define Overvoltage_LED_INPUT_SYNC 2u
#define Overvoltage_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Overvoltage_LED_NUM 2u
#define Overvoltage_LED_PORT GPIO_PRT9
#define Overvoltage_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Overvoltage_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Undervoltage_LED */
#define Undervoltage_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Undervoltage_LED_0_INBUF_ENABLED 0u
#define Undervoltage_LED_0_INIT_DRIVESTATE 0u
#define Undervoltage_LED_0_INIT_MUXSEL 0u
#define Undervoltage_LED_0_INPUT_SYNC 2u
#define Undervoltage_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Undervoltage_LED_0_NUM 3u
#define Undervoltage_LED_0_PORT GPIO_PRT9
#define Undervoltage_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Undervoltage_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Undervoltage_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Undervoltage_LED_INBUF_ENABLED 0u
#define Undervoltage_LED_INIT_DRIVESTATE 0u
#define Undervoltage_LED_INIT_MUXSEL 0u
#define Undervoltage_LED_INPUT_SYNC 2u
#define Undervoltage_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Undervoltage_LED_NUM 3u
#define Undervoltage_LED_PORT GPIO_PRT9
#define Undervoltage_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Undervoltage_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
